export { default as DashboardPage } from './DashboardPage'
export { default as ProductsPage } from './ProductsPage'
export { default as CategoriesPage } from './CategoriesPage'
export { default as OwnersPage } from './OwnersPage'
export { default as ProfilePage } from './ProfilePage'
export { default as UsersPage } from './UsersPage'
